[package]
name = "rust_server"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3.7"
rusqlite = "0.29.0"
argon2 = "0.4.0"
tera = "1.17.0"
chrono = "0.4.30"
rand = "0.9.0-beta.3"
lazy_static = "1.4.0"
actix-web = "4.0.0-rc.3"
tokio = { version = "1", features = ["full"] }
